/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../scripts/modules/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '../../../scripts/modules/footer.module';
import * as import8 from '../../../scripts/modules/shared.module';
import * as import9 from '../../../scripts/modules/header.module';
import * as import10 from '../../../scripts/modules/loader.module';
import * as import11 from '../../../scripts/modules/map.module';
import * as import12 from '../../../scripts/modules/weather.module';
import * as import13 from '@angular/common/src/localization';
import * as import14 from '@angular/core/src/application_init';
import * as import15 from '@angular/core/src/testability/testability';
import * as import16 from '@angular/core/src/application_ref';
import * as import17 from '@angular/core/src/linker/compiler';
import * as import18 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import19 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import20 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import21 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import22 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import23 from '@angular/core/src/linker/view_utils';
import * as import24 from '@angular/platform-browser/src/browser/title';
import * as import25 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import26 from '../../../scripts/services/WeatherDTOtoWeatherConverter';
import * as import27 from '../../../scripts/services/WeatherAPI';
import * as import28 from '../../../scripts/services/Logger';
import * as import29 from '../../../scripts/services/Profiler';
import * as import30 from '../../../scripts/services/Location';
import * as import31 from '@angular/core/src/di/injector';
import * as import32 from '../components/app.component.ngfactory';
import * as import33 from '@angular/core/src/application_tokens';
import * as import34 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import35 from '@angular/platform-browser/src/dom/events/key_events';
import * as import36 from '@angular/core/src/zone/ng_zone';
import * as import37 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import38 from '@angular/core/src/console';
import * as import39 from '@angular/core/src/i18n/tokens';
import * as import40 from '@angular/core/src/error_handler';
import * as import41 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import42 from '@angular/platform-browser/src/dom/animation_driver';
import * as import43 from '@angular/core/src/render/api';
import * as import44 from '@angular/core/src/security';
import * as import45 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import46 from '@angular/core/src/change_detection/differs/keyvalue_differs';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _FooterModule_5:import7.FooterModule;
  _SharedModule_6:import8.SharedModule;
  _HeaderModule_7:import9.HeaderModule;
  _LoaderModule_8:import10.LoaderModule;
  _MapModule_9:import11.MapModule;
  _WeatherModule_10:import12.WeatherModule;
  _AppModule_11:import1.AppModule;
  __LOCALE_ID_12:any;
  __NgLocalization_13:import13.NgLocaleLocalization;
  _ErrorHandler_14:any;
  _ApplicationInitStatus_15:import14.ApplicationInitStatus;
  _Testability_16:import15.Testability;
  _ApplicationRef__17:import16.ApplicationRef_;
  __ApplicationRef_18:any;
  __Compiler_19:import17.Compiler;
  __APP_ID_20:any;
  __DOCUMENT_21:any;
  __HAMMER_GESTURE_CONFIG_22:import18.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_23:any[];
  __EventManager_24:import19.EventManager;
  __DomSharedStylesHost_25:import20.DomSharedStylesHost;
  __AnimationDriver_26:any;
  __DomRootRenderer_27:import21.DomRootRenderer_;
  __RootRenderer_28:any;
  __DomSanitizer_29:import22.DomSanitizerImpl;
  __Sanitizer_30:any;
  __ViewUtils_31:import23.ViewUtils;
  __IterableDiffers_32:any;
  __KeyValueDiffers_33:any;
  __SharedStylesHost_34:any;
  __Title_35:import24.Title;
  __RadioControlRegistry_36:import25.RadioControlRegistry;
  __WeatherDTOtoWeatherConverter_37:import26.WeatherDTOtoWeatherConverter;
  __WeatherApiService_38:import27.WeatherApiService;
  __LoggerService_39:import28.LoggerService;
  __Profiler_40:import29.Profiler;
  __LocationService_41:import30.LocationService;
  constructor(parent:import31.Injector) {
    super(parent,[import32.AppComponentNgFactory],[import32.AppComponentNgFactory]);
  }
  get _LOCALE_ID_12():any {
    if ((this.__LOCALE_ID_12 == null)) { (this.__LOCALE_ID_12 = 'en-US'); }
    return this.__LOCALE_ID_12;
  }
  get _NgLocalization_13():import13.NgLocaleLocalization {
    if ((this.__NgLocalization_13 == null)) { (this.__NgLocalization_13 = new import13.NgLocaleLocalization(this._LOCALE_ID_12)); }
    return this.__NgLocalization_13;
  }
  get _ApplicationRef_18():any {
    if ((this.__ApplicationRef_18 == null)) { (this.__ApplicationRef_18 = this._ApplicationRef__17); }
    return this.__ApplicationRef_18;
  }
  get _Compiler_19():import17.Compiler {
    if ((this.__Compiler_19 == null)) { (this.__Compiler_19 = new import17.Compiler()); }
    return this.__Compiler_19;
  }
  get _APP_ID_20():any {
    if ((this.__APP_ID_20 == null)) { (this.__APP_ID_20 = import33._appIdRandomProviderFactory()); }
    return this.__APP_ID_20;
  }
  get _DOCUMENT_21():any {
    if ((this.__DOCUMENT_21 == null)) { (this.__DOCUMENT_21 = import4._document()); }
    return this.__DOCUMENT_21;
  }
  get _HAMMER_GESTURE_CONFIG_22():import18.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_22 == null)) { (this.__HAMMER_GESTURE_CONFIG_22 = new import18.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_22;
  }
  get _EVENT_MANAGER_PLUGINS_23():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_23 == null)) { (this.__EVENT_MANAGER_PLUGINS_23 = [
      new import34.DomEventsPlugin(),
      new import35.KeyEventsPlugin(),
      new import18.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_22)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_23;
  }
  get _EventManager_24():import19.EventManager {
    if ((this.__EventManager_24 == null)) { (this.__EventManager_24 = new import19.EventManager(this._EVENT_MANAGER_PLUGINS_23,this.parent.get(import36.NgZone))); }
    return this.__EventManager_24;
  }
  get _DomSharedStylesHost_25():import20.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_25 == null)) { (this.__DomSharedStylesHost_25 = new import20.DomSharedStylesHost(this._DOCUMENT_21)); }
    return this.__DomSharedStylesHost_25;
  }
  get _AnimationDriver_26():any {
    if ((this.__AnimationDriver_26 == null)) { (this.__AnimationDriver_26 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_26;
  }
  get _DomRootRenderer_27():import21.DomRootRenderer_ {
    if ((this.__DomRootRenderer_27 == null)) { (this.__DomRootRenderer_27 = new import21.DomRootRenderer_(this._DOCUMENT_21,this._EventManager_24,this._DomSharedStylesHost_25,this._AnimationDriver_26,this._APP_ID_20)); }
    return this.__DomRootRenderer_27;
  }
  get _RootRenderer_28():any {
    if ((this.__RootRenderer_28 == null)) { (this.__RootRenderer_28 = import37._createConditionalRootRenderer(this._DomRootRenderer_27,this.parent.get(import37.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_28;
  }
  get _DomSanitizer_29():import22.DomSanitizerImpl {
    if ((this.__DomSanitizer_29 == null)) { (this.__DomSanitizer_29 = new import22.DomSanitizerImpl()); }
    return this.__DomSanitizer_29;
  }
  get _Sanitizer_30():any {
    if ((this.__Sanitizer_30 == null)) { (this.__Sanitizer_30 = this._DomSanitizer_29); }
    return this.__Sanitizer_30;
  }
  get _ViewUtils_31():import23.ViewUtils {
    if ((this.__ViewUtils_31 == null)) { (this.__ViewUtils_31 = new import23.ViewUtils(this._RootRenderer_28,this._Sanitizer_30)); }
    return this.__ViewUtils_31;
  }
  get _IterableDiffers_32():any {
    if ((this.__IterableDiffers_32 == null)) { (this.__IterableDiffers_32 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_32;
  }
  get _KeyValueDiffers_33():any {
    if ((this.__KeyValueDiffers_33 == null)) { (this.__KeyValueDiffers_33 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_33;
  }
  get _SharedStylesHost_34():any {
    if ((this.__SharedStylesHost_34 == null)) { (this.__SharedStylesHost_34 = this._DomSharedStylesHost_25); }
    return this.__SharedStylesHost_34;
  }
  get _Title_35():import24.Title {
    if ((this.__Title_35 == null)) { (this.__Title_35 = new import24.Title()); }
    return this.__Title_35;
  }
  get _RadioControlRegistry_36():import25.RadioControlRegistry {
    if ((this.__RadioControlRegistry_36 == null)) { (this.__RadioControlRegistry_36 = new import25.RadioControlRegistry()); }
    return this.__RadioControlRegistry_36;
  }
  get _WeatherDTOtoWeatherConverter_37():import26.WeatherDTOtoWeatherConverter {
    if ((this.__WeatherDTOtoWeatherConverter_37 == null)) { (this.__WeatherDTOtoWeatherConverter_37 = new import26.WeatherDTOtoWeatherConverter()); }
    return this.__WeatherDTOtoWeatherConverter_37;
  }
  get _WeatherApiService_38():import27.WeatherApiService {
    if ((this.__WeatherApiService_38 == null)) { (this.__WeatherApiService_38 = new import27.WeatherApiService(this._WeatherDTOtoWeatherConverter_37)); }
    return this.__WeatherApiService_38;
  }
  get _LoggerService_39():import28.LoggerService {
    if ((this.__LoggerService_39 == null)) { (this.__LoggerService_39 = new import28.LoggerService()); }
    return this.__LoggerService_39;
  }
  get _Profiler_40():import29.Profiler {
    if ((this.__Profiler_40 == null)) { (this.__Profiler_40 = new import29.Profiler(this._LoggerService_39)); }
    return this.__Profiler_40;
  }
  get _LocationService_41():import30.LocationService {
    if ((this.__LocationService_41 == null)) { (this.__LocationService_41 = new import30.LocationService()); }
    return this.__LocationService_41;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._FooterModule_5 = new import7.FooterModule();
    this._SharedModule_6 = new import8.SharedModule();
    this._HeaderModule_7 = new import9.HeaderModule();
    this._LoaderModule_8 = new import10.LoaderModule();
    this._MapModule_9 = new import11.MapModule();
    this._WeatherModule_10 = new import12.WeatherModule();
    this._AppModule_11 = new import1.AppModule();
    this._ErrorHandler_14 = import4.errorHandler();
    this._ApplicationInitStatus_15 = new import14.ApplicationInitStatus(this.parent.get(import14.APP_INITIALIZER,(null as any)));
    this._Testability_16 = new import15.Testability(this.parent.get(import36.NgZone));
    this._ApplicationRef__17 = new import16.ApplicationRef_(this.parent.get(import36.NgZone),this.parent.get(import38.Console),this,this._ErrorHandler_14,this,this._ApplicationInitStatus_15,this.parent.get(import15.TestabilityRegistry,(null as any)),this._Testability_16);
    return this._AppModule_11;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.FooterModule)) { return this._FooterModule_5; }
    if ((token === import8.SharedModule)) { return this._SharedModule_6; }
    if ((token === import9.HeaderModule)) { return this._HeaderModule_7; }
    if ((token === import10.LoaderModule)) { return this._LoaderModule_8; }
    if ((token === import11.MapModule)) { return this._MapModule_9; }
    if ((token === import12.WeatherModule)) { return this._WeatherModule_10; }
    if ((token === import1.AppModule)) { return this._AppModule_11; }
    if ((token === import39.LOCALE_ID)) { return this._LOCALE_ID_12; }
    if ((token === import13.NgLocalization)) { return this._NgLocalization_13; }
    if ((token === import40.ErrorHandler)) { return this._ErrorHandler_14; }
    if ((token === import14.ApplicationInitStatus)) { return this._ApplicationInitStatus_15; }
    if ((token === import15.Testability)) { return this._Testability_16; }
    if ((token === import16.ApplicationRef_)) { return this._ApplicationRef__17; }
    if ((token === import16.ApplicationRef)) { return this._ApplicationRef_18; }
    if ((token === import17.Compiler)) { return this._Compiler_19; }
    if ((token === import33.APP_ID)) { return this._APP_ID_20; }
    if ((token === import41.DOCUMENT)) { return this._DOCUMENT_21; }
    if ((token === import18.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_22; }
    if ((token === import19.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_23; }
    if ((token === import19.EventManager)) { return this._EventManager_24; }
    if ((token === import20.DomSharedStylesHost)) { return this._DomSharedStylesHost_25; }
    if ((token === import42.AnimationDriver)) { return this._AnimationDriver_26; }
    if ((token === import21.DomRootRenderer)) { return this._DomRootRenderer_27; }
    if ((token === import43.RootRenderer)) { return this._RootRenderer_28; }
    if ((token === import22.DomSanitizer)) { return this._DomSanitizer_29; }
    if ((token === import44.Sanitizer)) { return this._Sanitizer_30; }
    if ((token === import23.ViewUtils)) { return this._ViewUtils_31; }
    if ((token === import45.IterableDiffers)) { return this._IterableDiffers_32; }
    if ((token === import46.KeyValueDiffers)) { return this._KeyValueDiffers_33; }
    if ((token === import20.SharedStylesHost)) { return this._SharedStylesHost_34; }
    if ((token === import24.Title)) { return this._Title_35; }
    if ((token === import25.RadioControlRegistry)) { return this._RadioControlRegistry_36; }
    if ((token === import26.WeatherDTOtoWeatherConverter)) { return this._WeatherDTOtoWeatherConverter_37; }
    if ((token === import27.WeatherApiService)) { return this._WeatherApiService_38; }
    if ((token === import28.LoggerService)) { return this._LoggerService_39; }
    if ((token === import29.Profiler)) { return this._Profiler_40; }
    if ((token === import30.LocationService)) { return this._LocationService_41; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__17.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);