/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../scripts/modules/weatherDetails.module';
import * as import2 from '@angular/http/src/http_module';
import * as import3 from '@angular/common/src/common_module';
import * as import4 from '../../../scripts/modules/shared.module';
import * as import5 from '@angular/router/src/router_module';
import * as import6 from '../../../scripts/modules/weather.module';
import * as import7 from '@angular/http/src/backends/browser_xhr';
import * as import8 from '@angular/http/src/base_response_options';
import * as import9 from '@angular/http/src/backends/xhr_backend';
import * as import10 from '@angular/http/src/base_request_options';
import * as import11 from '@angular/common/src/localization';
import * as import12 from '../../../scripts/services/WeatherDTOtoWeatherConverter';
import * as import13 from '../../../scripts/services/WeatherAPI';
import * as import14 from '../../../scripts/services/WeatherDetailsResolver';
import * as import15 from '@angular/core/src/di/injector';
import * as import16 from '@angular/core/src/i18n/tokens';
import * as import17 from '@angular/router/src/router';
import * as import18 from '@angular/http/src/interfaces';
import * as import19 from '@angular/http/src/http';
class WeatherDetailsModuleInjector extends import0.NgModuleInjector<import1.WeatherDetailsModule> {
  _HttpModule_0:import2.HttpModule;
  _CommonModule_1:import3.CommonModule;
  _SharedModule_2:import4.SharedModule;
  _RouterModule_3:import5.RouterModule;
  _WeatherModule_4:import6.WeatherModule;
  _WeatherDetailsModule_5:import1.WeatherDetailsModule;
  __BrowserXhr_6:import7.BrowserXhr;
  __ResponseOptions_7:import8.BaseResponseOptions;
  __XSRFStrategy_8:any;
  __XHRBackend_9:import9.XHRBackend;
  __RequestOptions_10:import10.BaseRequestOptions;
  __Http_11:any;
  __NgLocalization_12:import11.NgLocaleLocalization;
  __WeatherDTOtoWeatherConverter_13:import12.WeatherDTOtoWeatherConverter;
  __WeatherApiService_14:import13.WeatherApiService;
  __WeatherDetailsResolver_15:import14.WeatherDetailsResolver;
  constructor(parent:import15.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _BrowserXhr_6():import7.BrowserXhr {
    if ((this.__BrowserXhr_6 == null)) { (this.__BrowserXhr_6 = new import7.BrowserXhr()); }
    return this.__BrowserXhr_6;
  }
  get _ResponseOptions_7():import8.BaseResponseOptions {
    if ((this.__ResponseOptions_7 == null)) { (this.__ResponseOptions_7 = new import8.BaseResponseOptions()); }
    return this.__ResponseOptions_7;
  }
  get _XSRFStrategy_8():any {
    if ((this.__XSRFStrategy_8 == null)) { (this.__XSRFStrategy_8 = import2._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_8;
  }
  get _XHRBackend_9():import9.XHRBackend {
    if ((this.__XHRBackend_9 == null)) { (this.__XHRBackend_9 = new import9.XHRBackend(this._BrowserXhr_6,this._ResponseOptions_7,this._XSRFStrategy_8)); }
    return this.__XHRBackend_9;
  }
  get _RequestOptions_10():import10.BaseRequestOptions {
    if ((this.__RequestOptions_10 == null)) { (this.__RequestOptions_10 = new import10.BaseRequestOptions()); }
    return this.__RequestOptions_10;
  }
  get _Http_11():any {
    if ((this.__Http_11 == null)) { (this.__Http_11 = import2.httpFactory(this._XHRBackend_9,this._RequestOptions_10)); }
    return this.__Http_11;
  }
  get _NgLocalization_12():import11.NgLocaleLocalization {
    if ((this.__NgLocalization_12 == null)) { (this.__NgLocalization_12 = new import11.NgLocaleLocalization(this.parent.get(import16.LOCALE_ID))); }
    return this.__NgLocalization_12;
  }
  get _WeatherDTOtoWeatherConverter_13():import12.WeatherDTOtoWeatherConverter {
    if ((this.__WeatherDTOtoWeatherConverter_13 == null)) { (this.__WeatherDTOtoWeatherConverter_13 = new import12.WeatherDTOtoWeatherConverter()); }
    return this.__WeatherDTOtoWeatherConverter_13;
  }
  get _WeatherApiService_14():import13.WeatherApiService {
    if ((this.__WeatherApiService_14 == null)) { (this.__WeatherApiService_14 = new import13.WeatherApiService(this._WeatherDTOtoWeatherConverter_13,this._Http_11)); }
    return this.__WeatherApiService_14;
  }
  get _WeatherDetailsResolver_15():import14.WeatherDetailsResolver {
    if ((this.__WeatherDetailsResolver_15 == null)) { (this.__WeatherDetailsResolver_15 = new import14.WeatherDetailsResolver(this._WeatherApiService_14,this.parent.get(import17.Router))); }
    return this.__WeatherDetailsResolver_15;
  }
  createInternal():import1.WeatherDetailsModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._CommonModule_1 = new import3.CommonModule();
    this._SharedModule_2 = new import4.SharedModule();
    this._RouterModule_3 = new import5.RouterModule(this.parent.get(import5.ROUTER_FORROOT_GUARD,(null as any)));
    this._WeatherModule_4 = new import6.WeatherModule();
    this._WeatherDetailsModule_5 = new import1.WeatherDetailsModule();
    return this._WeatherDetailsModule_5;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import3.CommonModule)) { return this._CommonModule_1; }
    if ((token === import4.SharedModule)) { return this._SharedModule_2; }
    if ((token === import5.RouterModule)) { return this._RouterModule_3; }
    if ((token === import6.WeatherModule)) { return this._WeatherModule_4; }
    if ((token === import1.WeatherDetailsModule)) { return this._WeatherDetailsModule_5; }
    if ((token === import7.BrowserXhr)) { return this._BrowserXhr_6; }
    if ((token === import8.ResponseOptions)) { return this._ResponseOptions_7; }
    if ((token === import18.XSRFStrategy)) { return this._XSRFStrategy_8; }
    if ((token === import9.XHRBackend)) { return this._XHRBackend_9; }
    if ((token === import10.RequestOptions)) { return this._RequestOptions_10; }
    if ((token === import19.Http)) { return this._Http_11; }
    if ((token === import11.NgLocalization)) { return this._NgLocalization_12; }
    if ((token === import12.WeatherDTOtoWeatherConverter)) { return this._WeatherDTOtoWeatherConverter_13; }
    if ((token === import13.WeatherApiService)) { return this._WeatherApiService_14; }
    if ((token === import14.WeatherDetailsResolver)) { return this._WeatherDetailsResolver_15; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const WeatherDetailsModuleNgFactory:import0.NgModuleFactory<import1.WeatherDetailsModule> = new import0.NgModuleFactory(WeatherDetailsModuleInjector,import1.WeatherDetailsModule);