/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.footer[_ngcontent-%COMP%] {\r\n    text-align: center;\r\n    margin-top: 20px;\r\n    background-color: lightgrey;\r\n    height: 50px;\r\n    line-height: 50px;\r\n}'];