/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.loader[_ngcontent-%COMP%] {\r\n    background-color: white;\r\n    height: 100%;\r\n    position: fixed;\r\n    width: 100%;\r\n    z-index: 1000;\r\n    top: 0;\r\n    left: 0;\r\n    text-align: center;\r\n    display: inline-block;\r\n    vertical-align: middle;\r\n}\r\n.loader[_ngcontent-%COMP%]::before {\r\n    display: inline-block;\r\n    vertical-align: middle;\r\n    height: 100%;\r\n    content: "";\r\n}\r\n\r\n.loading-text[_ngcontent-%COMP%] {\r\n    display: inline-block;\r\n    vertical-align: middle;\r\n    font-weight: bold;\r\n}'];