/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.row[_ngcontent-%COMP%] {\r\n    display: table-row;\r\n}\r\n.cell[_ngcontent-%COMP%] {\r\n    display: table-cell;\r\n    vertical-align: middle;\r\n}\r\n\r\n.arrow-buttons[_ngcontent-%COMP%] {\r\n    width: 16px;\r\n    padding: 0;\r\n}\r\n\r\n.multiselect[_ngcontent-%COMP%] {\r\n    height: 70px;\r\n    min-width: 127px;\r\n}'];