/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.table-form[_ngcontent-%COMP%] {\r\n    margin-bottom: 20px;\r\n    margin-top: 20px;\r\n    background-color: lightsteelblue;\r\n    padding: 20px;\r\n    box-sizing: border-box;\r\n}\r\n.form-row[_ngcontent-%COMP%] {\r\n    display: table-row;\r\n    margin-top: 10px;\r\n}\r\n.form-cell[_ngcontent-%COMP%] {\r\n    display: table-cell;\r\n    vertical-align: middle;\r\n    padding-right: 10px;\r\n}'];