/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['table[_ngcontent-%COMP%] {\r\n    text-align: center;\r\n    margin-top: 20px;\r\n    border-collapse: collapse;\r\n    margin-bottom: 30px;\r\n}\r\nthead[_ngcontent-%COMP%] {\r\n    background-color: lightblue\r\n}\r\ntd[_ngcontent-%COMP%] {\r\n    width: 10%;\r\n    border: 1px solid black;\r\n    padding: 10px;\r\n}\r\n@media screen and (min-width: 900px) {\r\n    table[_ngcontent-%COMP%], .city-form[_ngcontent-%COMP%], .table-form[_ngcontent-%COMP%] {\r\n        width: 80%;\r\n        margin-left: auto;\r\n        margin-right: auto;\r\n    }\r\n}\r\n@media screen and (max-width: 899px) {\r\n    table[_ngcontent-%COMP%], .city-form[_ngcontent-%COMP%], .table-form[_ngcontent-%COMP%] {\r\n        width: 100%;\r\n    }\r\n}\r\n.user-weather-table[_ngcontent-%COMP%] {\r\n    margin-bottom: 20px;\r\n    margin-top: 20px;\r\n}\r\n.city-form[_ngcontent-%COMP%] {\r\n    margin-bottom: 10px;\r\n    background-color: lightsteelblue;\r\n    padding: 20px;\r\n    box-sizing: border-box;\r\n}\r\n.table-btn[_ngcontent-%COMP%] {\r\n    margin: 10px;\r\n    width: 70px;\r\n}'];