/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.wind[_ngcontent-%COMP%] {\r\n    display: table;\r\n    margin: auto;\r\n}\r\n.wind-icon[_ngcontent-%COMP%] {\r\n    background-image: url(images/arrow.png);\r\n    width: 30px;\r\n    height: 30px;\r\n    background-size: 30px 30px;\r\n    display: table-cell;\r\n    min-width: 30px;\r\n}\r\n.wind-speed[_ngcontent-%COMP%] {\r\n    display: table-cell;\r\n    padding-left: 5px;\r\n    vertical-align: middle;\r\n}'];