/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../scripts/components/cityWeatherSection.component';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../scripts/services/WeatherAPI';
import * as import9 from '../../../scripts/services/Logger';
import * as import10 from '../../css/weatherTable.css.shim';
import * as import11 from '../../../scripts/components/cityForm.component';
import * as import12 from './cityForm.component.ngfactory';
import * as import13 from '../../../scripts/components/cityWeatherTable.component';
import * as import14 from './cityWeatherTable.component.ngfactory';
export class Wrapper_CityWeatherSectionComponent {
  /*private*/ _eventHandler:Function;
  context:import0.CityWeatherSectionComponent;
  /*private*/ _changed:boolean;
  /*private*/ _changes:{[key: string]:any};
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  subscription0:any;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this._changes = {};
    this.context = new import0.CityWeatherSectionComponent(p0,p1,p2);
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
  }
  check_latitude(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.latitude = currValue;
      this._changes['latitude'] = new import1.SimpleChange(this._expr_0,currValue);
      this._expr_0 = currValue;
    }
  }
  check_longitude(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this._changed = true;
      this.context.longitude = currValue;
      this._changes['longitude'] = new import1.SimpleChange(this._expr_1,currValue);
      this._expr_1 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) {
      if (changed) {
        this.context.ngOnChanges(this._changes);
        this._changes = {};
      }
      if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); }
    }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any,emit0:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.loadingNotify.subscribe(_eventHandler.bind(view,'loadingNotify'))); }
  }
}
var renderType_CityWeatherSectionComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_CityWeatherSectionComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.CityWeatherSectionComponent>;
  _CityWeatherSectionComponent_0_3:Wrapper_CityWeatherSectionComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CityWeatherSectionComponent_Host0,renderType_CityWeatherSectionComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'city-weather-section',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_CityWeatherSectionComponent0(this.viewUtils,this,0,this._el_0);
    this._CityWeatherSectionComponent_0_3 = new Wrapper_CityWeatherSectionComponent(this.compView_0.ref,this.injectorGet(import8.WeatherApiService,this.parentIndex),this.injectorGet(import9.LoggerService,this.parentIndex));
    this.compView_0.create(this._CityWeatherSectionComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._CityWeatherSectionComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.CityWeatherSectionComponent) && (0 === requestNodeIndex))) { return this._CityWeatherSectionComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._CityWeatherSectionComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._CityWeatherSectionComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const CityWeatherSectionComponentNgFactory:import7.ComponentFactory<import0.CityWeatherSectionComponent> = new import7.ComponentFactory<import0.CityWeatherSectionComponent>('city-weather-section',View_CityWeatherSectionComponent_Host0,import0.CityWeatherSectionComponent);
const styles_CityWeatherSectionComponent:any[] = [import10.styles];
var renderType_CityWeatherSectionComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_CityWeatherSectionComponent,{});
export class View_CityWeatherSectionComponent0 extends import2.AppView<import0.CityWeatherSectionComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import2.AppView<import11.CityFormComponent>;
  _CityFormComponent_2_3:import12.Wrapper_CityFormComponent;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  compView_5:import2.AppView<import13.CityWeatherTableComponent>;
  _CityWeatherTableComponent_5_3:import14.Wrapper_CityWeatherTableComponent;
  _text_6:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_CityWeatherSectionComponent0,renderType_CityWeatherSectionComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckOnce);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','user-weather-table'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'city-form',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_2 = new import12.View_CityFormComponent0(this.viewUtils,this,2,this._el_2);
    this._CityFormComponent_2_3 = new import12.Wrapper_CityFormComponent();
    this.compView_2.create(this._CityFormComponent_2_3.context);
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'city-weather-table',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_5 = new import14.View_CityWeatherTableComponent0(this.viewUtils,this,5,this._el_5);
    this._CityWeatherTableComponent_5_3 = new import14.Wrapper_CityWeatherTableComponent();
    this.compView_5.create(this._CityWeatherTableComponent_5_3.context);
    this._text_6 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'addNotify',(null as any)),this.eventHandler(this.handleEvent_2));
    this._CityFormComponent_2_3.subscribe(this,this.eventHandler(this.handleEvent_2),true);
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_5,new import3.InlineArray4(4,'deleteNotify',(null as any),'selectNotify',(null as any)),this.eventHandler(this.handleEvent_5));
    this._CityWeatherTableComponent_5_3.subscribe(this,this.eventHandler(this.handleEvent_5),true,true);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.CityFormComponent) && (2 === requestNodeIndex))) { return this._CityFormComponent_2_3.context; }
    if (((token === import13.CityWeatherTableComponent) && (5 === requestNodeIndex))) { return this._CityWeatherTableComponent_5_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._CityFormComponent_2_3.ngDoCheck(this,this._el_2,throwOnChange)) { this.compView_2.markAsCheckOnce(); }
    const currVal_5_0_0:any = this.context.weatherList;
    this._CityWeatherTableComponent_5_3.check_weatherList(currVal_5_0_0,throwOnChange,false);
    if (this._CityWeatherTableComponent_5_3.ngDoCheck(this,this._el_5,throwOnChange)) { this.compView_5.markAsCheckOnce(); }
    this.compView_2.detectChanges(throwOnChange);
    this.compView_5.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_2.destroy();
    this.compView_5.destroy();
    this._CityFormComponent_2_3.ngOnDestroy();
    this._CityWeatherTableComponent_5_3.ngOnDestroy();
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'addNotify')) {
      const pd_sub_0:any = ((<any>this.context.add($event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_5(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'deleteNotify')) {
      const pd_sub_0:any = ((<any>this.context.remove($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'selectNotify')) {
      const pd_sub_1:any = ((<any>this.context.select($event)) !== false);
      result = (pd_sub_1 && result);
    }
    return result;
  }
}