/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../scripts/components/weatherDetails.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/change_detection';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/router/src/router_state';
import * as import9 from '../../css/weatherDetails.css.shim';
import * as import10 from '@angular/core/src/linker/view_container';
import * as import11 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import12 from '../../../scripts/pipes/kelvinToCelsius.pipe';
import * as import13 from '@angular/core/src/linker/template_ref';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from '../../../scripts/components/weatherIcon.component';
import * as import16 from './weatherIcon.component.ngfactory';
import * as import17 from '../../../scripts/components/windSection.component';
import * as import18 from './windSection.component.ngfactory';
export class Wrapper_WeatherDetailsComponent {
  /*private*/ _eventHandler:Function;
  context:import0.WeatherDetailsComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.WeatherDetailsComponent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_WeatherDetailsComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_WeatherDetailsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.WeatherDetailsComponent>;
  _WeatherDetailsComponent_0_3:Wrapper_WeatherDetailsComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_WeatherDetailsComponent_Host0,renderType_WeatherDetailsComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'weather-details',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_WeatherDetailsComponent0(this.viewUtils,this,0,this._el_0);
    this._WeatherDetailsComponent_0_3 = new Wrapper_WeatherDetailsComponent(this.injectorGet(import8.ActivatedRoute,this.parentIndex));
    this.compView_0.create(this._WeatherDetailsComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._WeatherDetailsComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.WeatherDetailsComponent) && (0 === requestNodeIndex))) { return this._WeatherDetailsComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._WeatherDetailsComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const WeatherDetailsComponentNgFactory:import7.ComponentFactory<import0.WeatherDetailsComponent> = new import7.ComponentFactory<import0.WeatherDetailsComponent>('weather-details',View_WeatherDetailsComponent_Host0,import0.WeatherDetailsComponent);
const styles_WeatherDetailsComponent:any[] = [import9.styles];
var renderType_WeatherDetailsComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_WeatherDetailsComponent,{});
export class View_WeatherDetailsComponent0 extends import1.AppView<import0.WeatherDetailsComponent> {
  _anchor_0:any;
  /*private*/ _vc_0:import10.ViewContainer;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import11.Wrapper_NgIf;
  _pipe_sgKelvinToCelsius_0:import12.KelvinToCelsiusPipe;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_WeatherDetailsComponent0,renderType_WeatherDetailsComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckOnce);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_0 = new import10.ViewContainer(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import13.TemplateRef_(this,0,this._anchor_0);
    this._NgIf_0_6 = new import11.Wrapper_NgIf(this._vc_0.vcRef,this._TemplateRef_0_5);
    this._pipe_sgKelvinToCelsius_0 = new import12.KelvinToCelsiusPipe();
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [this._anchor_0]),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import14.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.weather;
    this._NgIf_0_6.check_ngIf(currVal_0_0_0,throwOnChange,false);
    this._NgIf_0_6.ngDoCheck(this,this._anchor_0,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 0)) { return new View_WeatherDetailsComponent1(this.viewUtils,this,0,this._anchor_0,this._vc_0); }
    return (null as any);
  }
}
class View_WeatherDetailsComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _el_26:any;
  compView_26:import1.AppView<import15.WeatherIconComponent>;
  _WeatherIconComponent_26_3:import16.Wrapper_WeatherIconComponent;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _el_51:any;
  compView_51:import1.AppView<import17.WindSectionComponent>;
  _WindSectionComponent_51_3:import18.Wrapper_WindSectionComponent;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  /*private*/ _expr_67:any;
  /*private*/ _expr_68:any;
  /*private*/ _expr_69:any;
  /*private*/ _expr_70:any;
  /*private*/ _expr_71:any;
  _pipe_sgKelvinToCelsius_0_0:any;
  /*private*/ _expr_73:any;
  /*private*/ _expr_74:any;
  /*private*/ _expr_75:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import10.ViewContainer) {
    super(View_WeatherDetailsComponent1,renderType_WeatherDetailsComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_67 = import6.UNINITIALIZED;
    this._expr_68 = import6.UNINITIALIZED;
    this._expr_69 = import6.UNINITIALIZED;
    this._expr_70 = import6.UNINITIALIZED;
    this._expr_71 = import6.UNINITIALIZED;
    this._expr_73 = import6.UNINITIALIZED;
    this._expr_74 = import6.UNINITIALIZED;
    this._expr_75 = import6.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','details'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','header title'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','header'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Coordinate',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','col-md-4 col-xs-6'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','col-md-4 col-xs-6'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this._text_15 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_17 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','header'),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Overall Conditions',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_20 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_22 = import3.createRenderElement(this.renderer,this._el_20,'div',new import3.InlineArray2(2,'class','col-md-4 col-xs-6'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'',(null as any));
    this._text_24 = this.renderer.createText(this._el_20,'\n        ',(null as any));
    this._el_25 = import3.createRenderElement(this.renderer,this._el_20,'div',new import3.InlineArray2(2,'class','col-md-4 col-xs-6 conditions'),(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_25,'weather-icon',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_26 = new import16.View_WeatherIconComponent0(this.viewUtils,this,26,this._el_26);
    this._WeatherIconComponent_26_3 = new import16.Wrapper_WeatherIconComponent();
    this.compView_26.create(this._WeatherIconComponent_26_3.context);
    this._text_27 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._text_28 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_29 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','header'),(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'Main Parameters',(null as any));
    this._text_31 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'\n        ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_32,'div',new import3.InlineArray2(2,'class','col-md-4 col-xs-6'),(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'',(null as any));
    this._text_36 = this.renderer.createText(this._el_32,'\n        ',(null as any));
    this._el_37 = import3.createRenderElement(this.renderer,this._el_32,'div',new import3.InlineArray2(2,'class','col-md-4 col-xs-6'),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'',(null as any));
    this._text_39 = this.renderer.createText(this._el_32,'\n        ',(null as any));
    this._el_40 = import3.createRenderElement(this.renderer,this._el_32,'div',new import3.InlineArray2(2,'class','col-md-4 col-xs-6'),(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'',(null as any));
    this._text_42 = this.renderer.createText(this._el_32,'\n    ',(null as any));
    this._text_43 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','header'),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'Wind',(null as any));
    this._text_46 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_48 = this.renderer.createText(this._el_47,'\n        ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_47,'div',new import3.InlineArray2(2,'class','col-md-4 col-xs-6'),(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'Speed: ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_49,'wind-section',new import3.InlineArray2(2,'class','wind-details'),(null as any));
    this.compView_51 = new import18.View_WindSectionComponent0(this.viewUtils,this,51,this._el_51);
    this._WindSectionComponent_51_3 = new import18.Wrapper_WindSectionComponent();
    this.compView_51.create(this._WindSectionComponent_51_3.context);
    this._text_52 = this.renderer.createText(this._el_47,'\n    ',(null as any));
    this._text_53 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_54 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','header'),(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'Clouds',(null as any));
    this._text_56 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_57 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'\n        ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_57,'div',new import3.InlineArray2(2,'class','col-md-4 col-xs-6'),(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'',(null as any));
    this._text_61 = this.renderer.createText(this._el_57,'\n    ',(null as any));
    this._text_62 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._pipe_sgKelvinToCelsius_0_0 = import3.pureProxy1((<View_WeatherDetailsComponent0>this.parentView)._pipe_sgKelvinToCelsius_0.transform.bind((<View_WeatherDetailsComponent0>this.parentView)._pipe_sgKelvinToCelsius_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._text_62
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.WeatherIconComponent) && (26 === requestNodeIndex))) { return this._WeatherIconComponent_26_3.context; }
    if (((token === import17.WindSectionComponent) && (51 === requestNodeIndex))) { return this._WindSectionComponent_51_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import6.ValueUnwrapper();
    const currVal_26_0_0:any = this.parentView.context.weather.getDescription();
    this._WeatherIconComponent_26_3.check_description(currVal_26_0_0,throwOnChange,false);
    if (this._WeatherIconComponent_26_3.ngDoCheck(this,this._el_26,throwOnChange)) { this.compView_26.markAsCheckOnce(); }
    const currVal_51_0_0:any = this.parentView.context.weather.getWind();
    this._WindSectionComponent_51_3.check_wind(currVal_51_0_0,throwOnChange,false);
    if (this._WindSectionComponent_51_3.ngDoCheck(this,this._el_51,throwOnChange)) { this.compView_51.markAsCheckOnce(); }
    const currVal_67:any = import3.inlineInterpolate(1,'City: ',this.parentView.context.weather.getCity(),'');
    if (import3.checkBinding(throwOnChange,this._expr_67,currVal_67)) {
      this.renderer.setText(this._text_3,currVal_67);
      this._expr_67 = currVal_67;
    }
    const currVal_68:any = import3.inlineInterpolate(1,'Latitude: ',this.parentView.context.weather.getCoordinate().getLatitude(),'');
    if (import3.checkBinding(throwOnChange,this._expr_68,currVal_68)) {
      this.renderer.setText(this._text_11,currVal_68);
      this._expr_68 = currVal_68;
    }
    const currVal_69:any = import3.inlineInterpolate(1,'Longitude: ',this.parentView.context.weather.getCoordinate().getLongitude(),'');
    if (import3.checkBinding(throwOnChange,this._expr_69,currVal_69)) {
      this.renderer.setText(this._text_14,currVal_69);
      this._expr_69 = currVal_69;
    }
    const currVal_70:any = import3.inlineInterpolate(1,'Description: ',this.parentView.context.weather.getDescription(),'');
    if (import3.checkBinding(throwOnChange,this._expr_70,currVal_70)) {
      this.renderer.setText(this._text_23,currVal_70);
      this._expr_70 = currVal_70;
    }
    valUnwrapper.reset();
    const currVal_71:any = import3.inlineInterpolate(1,'Temperature: ',valUnwrapper.unwrap(import3.castByValue(this._pipe_sgKelvinToCelsius_0_0,(<View_WeatherDetailsComponent0>this.parentView)._pipe_sgKelvinToCelsius_0.transform)(this.parentView.context.weather.getMainParams().getTemperature())),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_71,currVal_71))) {
      this.renderer.setText(this._text_35,currVal_71);
      this._expr_71 = currVal_71;
    }
    const currVal_73:any = import3.inlineInterpolate(1,'Humidity: ',this.parentView.context.weather.getMainParams().getHumidity(),'');
    if (import3.checkBinding(throwOnChange,this._expr_73,currVal_73)) {
      this.renderer.setText(this._text_38,currVal_73);
      this._expr_73 = currVal_73;
    }
    const currVal_74:any = import3.inlineInterpolate(1,'Pressure: ',this.parentView.context.weather.getMainParams().getPressure(),'');
    if (import3.checkBinding(throwOnChange,this._expr_74,currVal_74)) {
      this.renderer.setText(this._text_41,currVal_74);
      this._expr_74 = currVal_74;
    }
    const currVal_75:any = import3.inlineInterpolate(1,'All: ',this.parentView.context.weather.getCloud().getAll(),'');
    if (import3.checkBinding(throwOnChange,this._expr_75,currVal_75)) {
      this.renderer.setText(this._text_60,currVal_75);
      this._expr_75 = currVal_75;
    }
    this.compView_26.detectChanges(throwOnChange);
    this.compView_51.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_26.destroy();
    this.compView_51.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}