/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../scripts/components/weatherIcon.component';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../node_modules/@angular/common/src/directives/ng_switch.ngfactory';
import * as import9 from '@angular/core/src/linker/view_container';
import * as import10 from '@angular/core/src/linker/template_ref';
import * as import11 from '@angular/common/src/directives/ng_switch';
export class Wrapper_WeatherIconComponent {
  /*private*/ _eventHandler:Function;
  context:import0.WeatherIconComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  constructor() {
    this._changed = false;
    this.context = new import0.WeatherIconComponent();
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_description(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.description = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_WeatherIconComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_WeatherIconComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.WeatherIconComponent>;
  _WeatherIconComponent_0_3:Wrapper_WeatherIconComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_WeatherIconComponent_Host0,renderType_WeatherIconComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'weather-icon',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_WeatherIconComponent0(this.viewUtils,this,0,this._el_0);
    this._WeatherIconComponent_0_3 = new Wrapper_WeatherIconComponent();
    this.compView_0.create(this._WeatherIconComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._WeatherIconComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.WeatherIconComponent) && (0 === requestNodeIndex))) { return this._WeatherIconComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._WeatherIconComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange)) { this.compView_0.markAsCheckOnce(); }
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const WeatherIconComponentNgFactory:import7.ComponentFactory<import0.WeatherIconComponent> = new import7.ComponentFactory<import0.WeatherIconComponent>('weather-icon',View_WeatherIconComponent_Host0,import0.WeatherIconComponent);
const styles_WeatherIconComponent:any[] = ([] as any[]);
var renderType_WeatherIconComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,styles_WeatherIconComponent,{});
export class View_WeatherIconComponent0 extends import2.AppView<import0.WeatherIconComponent> {
  _el_0:any;
  _NgSwitch_0_3:import8.Wrapper_NgSwitch;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import9.ViewContainer;
  _TemplateRef_2_5:any;
  _NgSwitchCase_2_6:import8.Wrapper_NgSwitchCase;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import9.ViewContainer;
  _TemplateRef_4_5:any;
  _NgSwitchCase_4_6:import8.Wrapper_NgSwitchCase;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _vc_6:import9.ViewContainer;
  _TemplateRef_6_5:any;
  _NgSwitchCase_6_6:import8.Wrapper_NgSwitchCase;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _vc_8:import9.ViewContainer;
  _TemplateRef_8_5:any;
  _NgSwitchCase_8_6:import8.Wrapper_NgSwitchCase;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _vc_10:import9.ViewContainer;
  _TemplateRef_10_5:any;
  _NgSwitchCase_10_6:import8.Wrapper_NgSwitchCase;
  _text_11:any;
  _anchor_12:any;
  /*private*/ _vc_12:import9.ViewContainer;
  _TemplateRef_12_5:any;
  _NgSwitchCase_12_6:import8.Wrapper_NgSwitchCase;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _vc_14:import9.ViewContainer;
  _TemplateRef_14_5:any;
  _NgSwitchCase_14_6:import8.Wrapper_NgSwitchCase;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _vc_16:import9.ViewContainer;
  _TemplateRef_16_5:any;
  _NgSwitchCase_16_6:import8.Wrapper_NgSwitchCase;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _vc_18:import9.ViewContainer;
  _TemplateRef_18_5:any;
  _NgSwitchCase_18_6:import8.Wrapper_NgSwitchCase;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _vc_20:import9.ViewContainer;
  _TemplateRef_20_5:any;
  _NgSwitchCase_20_6:import8.Wrapper_NgSwitchCase;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _vc_22:import9.ViewContainer;
  _TemplateRef_22_5:any;
  _NgSwitchCase_22_6:import8.Wrapper_NgSwitchCase;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _vc_24:import9.ViewContainer;
  _TemplateRef_24_5:any;
  _NgSwitchDefault_24_6:import8.Wrapper_NgSwitchDefault;
  _text_25:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_WeatherIconComponent0,renderType_WeatherIconComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckOnce);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSwitch_0_3 = new import8.Wrapper_NgSwitch();
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import9.ViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import10.TemplateRef_(this,2,this._anchor_2);
    this._NgSwitchCase_2_6 = new import8.Wrapper_NgSwitchCase(this._vc_2.vcRef,this._TemplateRef_2_5,this._NgSwitch_0_3.context);
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_4 = new import9.ViewContainer(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import10.TemplateRef_(this,4,this._anchor_4);
    this._NgSwitchCase_4_6 = new import8.Wrapper_NgSwitchCase(this._vc_4.vcRef,this._TemplateRef_4_5,this._NgSwitch_0_3.context);
    this._text_5 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_6 = new import9.ViewContainer(6,0,this,this._anchor_6);
    this._TemplateRef_6_5 = new import10.TemplateRef_(this,6,this._anchor_6);
    this._NgSwitchCase_6_6 = new import8.Wrapper_NgSwitchCase(this._vc_6.vcRef,this._TemplateRef_6_5,this._NgSwitch_0_3.context);
    this._text_7 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_8 = new import9.ViewContainer(8,0,this,this._anchor_8);
    this._TemplateRef_8_5 = new import10.TemplateRef_(this,8,this._anchor_8);
    this._NgSwitchCase_8_6 = new import8.Wrapper_NgSwitchCase(this._vc_8.vcRef,this._TemplateRef_8_5,this._NgSwitch_0_3.context);
    this._text_9 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_10 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_10 = new import9.ViewContainer(10,0,this,this._anchor_10);
    this._TemplateRef_10_5 = new import10.TemplateRef_(this,10,this._anchor_10);
    this._NgSwitchCase_10_6 = new import8.Wrapper_NgSwitchCase(this._vc_10.vcRef,this._TemplateRef_10_5,this._NgSwitch_0_3.context);
    this._text_11 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_12 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_12 = new import9.ViewContainer(12,0,this,this._anchor_12);
    this._TemplateRef_12_5 = new import10.TemplateRef_(this,12,this._anchor_12);
    this._NgSwitchCase_12_6 = new import8.Wrapper_NgSwitchCase(this._vc_12.vcRef,this._TemplateRef_12_5,this._NgSwitch_0_3.context);
    this._text_13 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_14 = new import9.ViewContainer(14,0,this,this._anchor_14);
    this._TemplateRef_14_5 = new import10.TemplateRef_(this,14,this._anchor_14);
    this._NgSwitchCase_14_6 = new import8.Wrapper_NgSwitchCase(this._vc_14.vcRef,this._TemplateRef_14_5,this._NgSwitch_0_3.context);
    this._text_15 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_16 = new import9.ViewContainer(16,0,this,this._anchor_16);
    this._TemplateRef_16_5 = new import10.TemplateRef_(this,16,this._anchor_16);
    this._NgSwitchCase_16_6 = new import8.Wrapper_NgSwitchCase(this._vc_16.vcRef,this._TemplateRef_16_5,this._NgSwitch_0_3.context);
    this._text_17 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_18 = new import9.ViewContainer(18,0,this,this._anchor_18);
    this._TemplateRef_18_5 = new import10.TemplateRef_(this,18,this._anchor_18);
    this._NgSwitchCase_18_6 = new import8.Wrapper_NgSwitchCase(this._vc_18.vcRef,this._TemplateRef_18_5,this._NgSwitch_0_3.context);
    this._text_19 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_20 = new import9.ViewContainer(20,0,this,this._anchor_20);
    this._TemplateRef_20_5 = new import10.TemplateRef_(this,20,this._anchor_20);
    this._NgSwitchCase_20_6 = new import8.Wrapper_NgSwitchCase(this._vc_20.vcRef,this._TemplateRef_20_5,this._NgSwitch_0_3.context);
    this._text_21 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_22 = new import9.ViewContainer(22,0,this,this._anchor_22);
    this._TemplateRef_22_5 = new import10.TemplateRef_(this,22,this._anchor_22);
    this._NgSwitchCase_22_6 = new import8.Wrapper_NgSwitchCase(this._vc_22.vcRef,this._TemplateRef_22_5,this._NgSwitch_0_3.context);
    this._text_23 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_24 = new import9.ViewContainer(24,0,this,this._anchor_24);
    this._TemplateRef_24_5 = new import10.TemplateRef_(this,24,this._anchor_24);
    this._NgSwitchDefault_24_6 = new import8.Wrapper_NgSwitchDefault(this._vc_24.vcRef,this._TemplateRef_24_5,this._NgSwitch_0_3.context);
    this._text_25 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._anchor_10,
      this._text_11,
      this._anchor_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._anchor_24,
      this._text_25
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import11.NgSwitchCase) && (2 === requestNodeIndex))) { return this._NgSwitchCase_2_6.context; }
    if (((token === import10.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import11.NgSwitchCase) && (4 === requestNodeIndex))) { return this._NgSwitchCase_4_6.context; }
    if (((token === import10.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import11.NgSwitchCase) && (6 === requestNodeIndex))) { return this._NgSwitchCase_6_6.context; }
    if (((token === import10.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import11.NgSwitchCase) && (8 === requestNodeIndex))) { return this._NgSwitchCase_8_6.context; }
    if (((token === import10.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_5; }
    if (((token === import11.NgSwitchCase) && (10 === requestNodeIndex))) { return this._NgSwitchCase_10_6.context; }
    if (((token === import10.TemplateRef) && (12 === requestNodeIndex))) { return this._TemplateRef_12_5; }
    if (((token === import11.NgSwitchCase) && (12 === requestNodeIndex))) { return this._NgSwitchCase_12_6.context; }
    if (((token === import10.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import11.NgSwitchCase) && (14 === requestNodeIndex))) { return this._NgSwitchCase_14_6.context; }
    if (((token === import10.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import11.NgSwitchCase) && (16 === requestNodeIndex))) { return this._NgSwitchCase_16_6.context; }
    if (((token === import10.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import11.NgSwitchCase) && (18 === requestNodeIndex))) { return this._NgSwitchCase_18_6.context; }
    if (((token === import10.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_5; }
    if (((token === import11.NgSwitchCase) && (20 === requestNodeIndex))) { return this._NgSwitchCase_20_6.context; }
    if (((token === import10.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import11.NgSwitchCase) && (22 === requestNodeIndex))) { return this._NgSwitchCase_22_6.context; }
    if (((token === import10.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import11.NgSwitchDefault) && (24 === requestNodeIndex))) { return this._NgSwitchDefault_24_6.context; }
    if (((token === import11.NgSwitch) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._NgSwitch_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.description;
    this._NgSwitch_0_3.check_ngSwitch(currVal_0_0_0,throwOnChange,false);
    this._NgSwitch_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_2_0_0:any = 'clear sky';
    this._NgSwitchCase_2_6.check_ngSwitchCase(currVal_2_0_0,throwOnChange,false);
    this._NgSwitchCase_2_6.ngDoCheck(this,this._anchor_2,throwOnChange);
    const currVal_4_0_0:any = 'few clouds';
    this._NgSwitchCase_4_6.check_ngSwitchCase(currVal_4_0_0,throwOnChange,false);
    this._NgSwitchCase_4_6.ngDoCheck(this,this._anchor_4,throwOnChange);
    const currVal_6_0_0:any = 'scattered clouds';
    this._NgSwitchCase_6_6.check_ngSwitchCase(currVal_6_0_0,throwOnChange,false);
    this._NgSwitchCase_6_6.ngDoCheck(this,this._anchor_6,throwOnChange);
    const currVal_8_0_0:any = 'broken clouds';
    this._NgSwitchCase_8_6.check_ngSwitchCase(currVal_8_0_0,throwOnChange,false);
    this._NgSwitchCase_8_6.ngDoCheck(this,this._anchor_8,throwOnChange);
    const currVal_10_0_0:any = 'overcast clouds';
    this._NgSwitchCase_10_6.check_ngSwitchCase(currVal_10_0_0,throwOnChange,false);
    this._NgSwitchCase_10_6.ngDoCheck(this,this._anchor_10,throwOnChange);
    const currVal_12_0_0:any = 'shower rain';
    this._NgSwitchCase_12_6.check_ngSwitchCase(currVal_12_0_0,throwOnChange,false);
    this._NgSwitchCase_12_6.ngDoCheck(this,this._anchor_12,throwOnChange);
    const currVal_14_0_0:any = 'rain';
    this._NgSwitchCase_14_6.check_ngSwitchCase(currVal_14_0_0,throwOnChange,false);
    this._NgSwitchCase_14_6.ngDoCheck(this,this._anchor_14,throwOnChange);
    const currVal_16_0_0:any = 'thunderstorm';
    this._NgSwitchCase_16_6.check_ngSwitchCase(currVal_16_0_0,throwOnChange,false);
    this._NgSwitchCase_16_6.ngDoCheck(this,this._anchor_16,throwOnChange);
    const currVal_18_0_0:any = 'light snow';
    this._NgSwitchCase_18_6.check_ngSwitchCase(currVal_18_0_0,throwOnChange,false);
    this._NgSwitchCase_18_6.ngDoCheck(this,this._anchor_18,throwOnChange);
    const currVal_20_0_0:any = 'snow';
    this._NgSwitchCase_20_6.check_ngSwitchCase(currVal_20_0_0,throwOnChange,false);
    this._NgSwitchCase_20_6.ngDoCheck(this,this._anchor_20,throwOnChange);
    const currVal_22_0_0:any = 'mist';
    this._NgSwitchCase_22_6.check_ngSwitchCase(currVal_22_0_0,throwOnChange,false);
    this._NgSwitchCase_22_6.ngDoCheck(this,this._anchor_22,throwOnChange);
    this._NgSwitchDefault_24_6.ngDoCheck(this,this._anchor_24,throwOnChange);
    this._vc_2.detectChangesInNestedViews(throwOnChange);
    this._vc_4.detectChangesInNestedViews(throwOnChange);
    this._vc_6.detectChangesInNestedViews(throwOnChange);
    this._vc_8.detectChangesInNestedViews(throwOnChange);
    this._vc_10.detectChangesInNestedViews(throwOnChange);
    this._vc_12.detectChangesInNestedViews(throwOnChange);
    this._vc_14.detectChangesInNestedViews(throwOnChange);
    this._vc_16.detectChangesInNestedViews(throwOnChange);
    this._vc_18.detectChangesInNestedViews(throwOnChange);
    this._vc_20.detectChangesInNestedViews(throwOnChange);
    this._vc_22.detectChangesInNestedViews(throwOnChange);
    this._vc_24.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._vc_4.destroyNestedViews();
    this._vc_6.destroyNestedViews();
    this._vc_8.destroyNestedViews();
    this._vc_10.destroyNestedViews();
    this._vc_12.destroyNestedViews();
    this._vc_14.destroyNestedViews();
    this._vc_16.destroyNestedViews();
    this._vc_18.destroyNestedViews();
    this._vc_20.destroyNestedViews();
    this._vc_22.destroyNestedViews();
    this._vc_24.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 2)) { return new View_WeatherIconComponent1(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    if ((nodeIndex == 4)) { return new View_WeatherIconComponent2(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    if ((nodeIndex == 6)) { return new View_WeatherIconComponent3(this.viewUtils,this,6,this._anchor_6,this._vc_6); }
    if ((nodeIndex == 8)) { return new View_WeatherIconComponent4(this.viewUtils,this,8,this._anchor_8,this._vc_8); }
    if ((nodeIndex == 10)) { return new View_WeatherIconComponent5(this.viewUtils,this,10,this._anchor_10,this._vc_10); }
    if ((nodeIndex == 12)) { return new View_WeatherIconComponent6(this.viewUtils,this,12,this._anchor_12,this._vc_12); }
    if ((nodeIndex == 14)) { return new View_WeatherIconComponent7(this.viewUtils,this,14,this._anchor_14,this._vc_14); }
    if ((nodeIndex == 16)) { return new View_WeatherIconComponent8(this.viewUtils,this,16,this._anchor_16,this._vc_16); }
    if ((nodeIndex == 18)) { return new View_WeatherIconComponent9(this.viewUtils,this,18,this._anchor_18,this._vc_18); }
    if ((nodeIndex == 20)) { return new View_WeatherIconComponent10(this.viewUtils,this,20,this._anchor_20,this._vc_20); }
    if ((nodeIndex == 22)) { return new View_WeatherIconComponent11(this.viewUtils,this,22,this._anchor_22,this._vc_22); }
    if ((nodeIndex == 24)) { return new View_WeatherIconComponent12(this.viewUtils,this,24,this._anchor_24,this._vc_24); }
    return (null as any);
  }
}
class View_WeatherIconComponent1 extends import2.AppView<any> {
  _el_0:any;
  _el_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_WeatherIconComponent1,renderType_WeatherIconComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray2(2,'src','images/weather/sun.png'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_WeatherIconComponent2 extends import2.AppView<any> {
  _el_0:any;
  _el_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_WeatherIconComponent2,renderType_WeatherIconComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray2(2,'src','images/weather/clouds1.png'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_WeatherIconComponent3 extends import2.AppView<any> {
  _el_0:any;
  _el_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_WeatherIconComponent3,renderType_WeatherIconComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray2(2,'src','images/weather/clouds2.png'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_WeatherIconComponent4 extends import2.AppView<any> {
  _el_0:any;
  _el_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_WeatherIconComponent4,renderType_WeatherIconComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray2(2,'src','images/weather/clouds3.png'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_WeatherIconComponent5 extends import2.AppView<any> {
  _el_0:any;
  _el_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_WeatherIconComponent5,renderType_WeatherIconComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray2(2,'src','images/weather/clouds3.png'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_WeatherIconComponent6 extends import2.AppView<any> {
  _el_0:any;
  _el_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_WeatherIconComponent6,renderType_WeatherIconComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray2(2,'src','images/weather/rain1.png'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_WeatherIconComponent7 extends import2.AppView<any> {
  _el_0:any;
  _el_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_WeatherIconComponent7,renderType_WeatherIconComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray2(2,'src','images/weather/rain2.png'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_WeatherIconComponent8 extends import2.AppView<any> {
  _el_0:any;
  _el_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_WeatherIconComponent8,renderType_WeatherIconComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray2(2,'src','images/weather/thunderstorm.png'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_WeatherIconComponent9 extends import2.AppView<any> {
  _el_0:any;
  _el_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_WeatherIconComponent9,renderType_WeatherIconComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray2(2,'src','images/weather/snow.png'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_WeatherIconComponent10 extends import2.AppView<any> {
  _el_0:any;
  _el_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_WeatherIconComponent10,renderType_WeatherIconComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray2(2,'src','images/weather/snow.png'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_WeatherIconComponent11 extends import2.AppView<any> {
  _el_0:any;
  _el_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_WeatherIconComponent11,renderType_WeatherIconComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,this._el_0,'img',new import3.InlineArray2(2,'src','images/weather/mist.png'),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._el_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_WeatherIconComponent12 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import9.ViewContainer) {
    super(View_WeatherIconComponent12,renderType_WeatherIconComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'',this.parentView.context.description,'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}